spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop # MVCC=TRUE(??) ??? ?? ?? ??? ????? ? ? ?? ????? ?
    username: sa
    password:
    driver-class-name: org.h2.Driver # db connection? ??? DB ?? ??? ??

  jpa:
    hibernate:
      ddl-auto: create # ? ??? entity? ?? ?? ???? ??? ?? ??
    properties:
      hibernate:
        show_sql: true # system.out?? jpa? hibernate? ???? ?? sql? ??
        format_sql: true

logging:
  level:
   org.hibernate.sql: debug # logger? ?? jpa? hibernate? ???? ?? sql? ??
#  org.hibernate.type: trace # ?? ???? ??
